  version: "3.0"    
  services:    
    db:    
      ports:    
        - '5432:5432'    
      image: postgres    
      environment:    
        POSTGRES_USER: 'vocascan'    
        POSTGRES_PASSWORD: 'vocascan'    
        POSTGRES_DB: 'vocascan'    
      volumes:    
        - './database:/var/lib/postgresql/data'  
