version: '3.8'
services:
  vocascan:
    image: vocascan/vocascan-server:latest
    restart: always
    tty: true
    depends_on:
      - db
    environment:
      VOCASCAN_CONFIG: '/etc/vocascan/vocascan.config.js'
    ports:
      - '8000:8000'
    volumes:
      - './vocascan.config.js:/etc/vocascan/vocascan.config.js:ro'
  db:
    image: postgres
    environment:
      POSTGRES_USER: 'vocascan'
      POSTGRES_PASSWORD: 'vocascan'
      POSTGRES_DB: 'vocascan'
    volumes:
      - './database:/var/lib/postgresql/data'
